import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import BaseLayout from "~/components/shared/BaseLayout";
import ScrollToTopButton from "~/components/shared/ScrollToTopButton";
import { ThemeProvider } from "~/components/shared/theme-provider";
import { ToastProvider } from "~/components/ui/toast";
import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
	title: "Wheel Verse",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" suppressHydrationWarning className={`${geist.variable}`}>
			<body>
				<TRPCReactProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<SessionProvider>
						<BaseLayout>
							<ToastProvider>
								{children}
								<ScrollToTopButton />
							</ToastProvider>
						</BaseLayout>
						</SessionProvider>
					</ThemeProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
